version: '3.3'

services:
  mongo:
    image: mongo:latest

  serv:
    image: pipdevs/pip-services-accounts-node
    depends_on:
      - mongo
    environment:
      - MONGO_ENABLED=true
    ports:
      - "8080:8080"


  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    command: ${TEST_CMD:-bash -c "dotnet test Test/Test.csproj"}
    

